### PR TITLE
Add Security CI: CodeQL + Dependency Review

### PR DESCRIPTION
**Pull request by jentfoo**
This PR adds standard Security CI we run on all active repos and forks.  CodeQL will provide static analysis on golang, and dependency review will help ensure we don't add any dependencies with vulnerabilities or unexpected licenses.

### CODE REVIEW

**Comment by jentfoo** [comment]
CodeQL Python run was from a repo configuration.  This workflow will replace the UI configuration, but I have immediately removed `python` from the language list.

**Comment by jentfoo** [comment]
Go analyze failed because results can't be submitted when the default config is applied:
> CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled

Merging this config is ideal and will fix this.

**Comment by wadells** [comment]
It looks like the `teleport` branch is currently in sync with the upstream.  Did you chat with the cloud team at all about what the future of this repo is?  Are we going to develop new or reintegrate old custom code?

I ask because I would love it if we could archive the repo and use the upstream instead of adding moving parts/divergence.

I know there has been some other chatter/work on this repo in the past couple hours -- I'm just out of the loop and looking for context before I sign off.

@logand22 maybe you can chime in here?

**Comment by logand22** [comment]
> or reintegrate old custom code?

This. Until https://github.com/cert-manager/cert-manager/issues/5430 gains traction it seems like we'll continue to use this fork as it reduced our onboarding time drastically.

**Review by wadells — APPROVED** [review]

**Pull request merged**
